config/routes.rb
Rails.application.routes.draw do

  
  root 'muppets#client'
  
  resources :muppets

end

app/models/muppet.rb
class Muppet < ActiveRecord::Base
  validates :name, presence: true
  validates :image_url, presence: true
end

app/controllers/_api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session
  
  def index
    @muppets = Muppet.all
    render :json => @muppets
  end

  def show
    @muppet = Muppet.find(params[:id])
    render :json => @muppet
  end

  def create
    @muppet = Muppet.new(muppet_params)
    
    if @muppet.save
      render :json => @muppet
    else
      render :json => { :errors => @muppet.errors.full_messages }, :status => 422
    end
  end

  def update
    @muppet = Muppet.find(params[:id])
    
    if @muppet.update(muppet_params)
      render :json => @muppet
    else
      render :json => { :errors => @muppet.errors.full_messages }, :status => 422
    end
  end

  def destroy
    @muppet = Muppet.find(params[:id])
    if @muppet.destroy
      render :json => @muppet
    else
      render :json => { :errors => @muppet.errors.full_messages }, :status => 422
    end
  end

  private

  def muppet_params
    params.permit(:name, :image_url)
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session
  
  def index
    @muppets = Muppet.all
    render :json => @muppets
  end

  def show
    @muppet = Muppet.find(params[:id])
    render :json => @muppet
  end

  def create
    @muppet = Muppet.new(muppet_params)
    
    if @muppet.save
      render :json => @muppet
    else
      render :json => { :errors => @muppet.errors.full_messages }, :status => 422
    end
  end

  def update
    @muppet = Muppet.find(params[:id])
    
    if @muppet.update(muppet_params)
      render :json => @muppet
    else
      render :json => { :errors => @muppet.errors.full_messages }, :status => 422
    end
  end

  def destroy
    @muppet = Muppet.find(params[:id])
    if @muppet.destroy
      render :json => @muppet
    else
      render :json => { :errors => @muppet.errors.full_messages }, :status => 422
    end
  end

  private

  def muppet_params
    params.permit(:name, :image_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/muppets_controller.rb
class MuppetsController < ApplicationController
  def index
    @muppets = Muppet.all
  end

  def show
    @muppet = Muppet.find(params[:id])
  end

  def new
    @muppet = Muppet.new
  end

  def create
    @muppet = Muppet.new(muppet_params)
    
    if @muppet.save
      redirect_to @muppet
    else
      render :new
    end
  end

  def edit
    @muppet = Muppet.find(params[:id])
  end

  def update
    @muppet = Muppet.find(params[:id])
    
    if @muppet.update(muppet_params)
      redirect_to @muppet
    else
      render :edit
    end
  end

  def destroy
    @muppet = Muppet.find(params[:id])
    if @muppet.destroy
      redirect_to muppets_path
    else
      render :edit
    end
  end

  def client
  end
  
  private

  def muppet_params
    params.require(:muppet).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MuppetsApp</title>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/muppets/_form.html.erb
<% if @muppet.errors.any? %>
  <b>Errors:</b>
  <ul>
  <% @muppet.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @muppet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.submit %>
<% end %>

app/views/muppets/client.html.erb
<%= link_to 'Basic Rails Client', muppets_path %>
<h1>Muppets, API Client</h1>

<form id="muppets-form">
  <label>Name: <input type="text" name="name"></label>
  <label>Image URL: <input type="text" name="image_url"></label>
  <input type="submit" value="Submit">
</form>

<ul id="muppets-list"></ul>

app/views/muppets/edit.html.erb
<h1>Edit <%= @muppet.name %></h1>

<%= render 'form' %>

app/views/muppets/index.html.erb
<h1>Muppets</h1>

<ul>
<% @muppets.each do |muppet| %>
  <li><%= link_to muppet.name, muppet %></li>
<% end %>
</ul>

<%= link_to 'Add a muppet', new_muppet_path %>

app/views/muppets/new.html.erb
<h1>Add a muppet</h1>

<%= render 'form' %>

app/views/muppets/show.html.erb
<p><%= link_to "Muppets", muppets_path %> / <%= @muppet.name %></p>  

<h1><%= @muppet.name %></h1>
<%= image_tag @muppet.image_url %>

<p><%= link_to 'Edit', edit_muppet_path(@muppet) %> | <%= link_to 'Destroy', muppet_path(@muppet), :method => :delete, :'data-confirm' => 'Are you sure?' %></p>

<%= form_for @muppet, :method => :delete do |f| %>
  <%= f.submit 'Destroy' %>
<% end %>